sudo: required

language: node_js

node_js:
  - '8'

cache:
  yarn: true

before_script:
  - yarn run lint

script:
  - yarn run build
  - yarn run build-min
  - yarn test

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: rwOfAUgTDxV1Ec6sKuvMoGLhTooAfLZ0H/4G2yeU5rbr5CHKDDryam875ykVsBk2uo2/yo8BCXPbJ56O835yxj7eVLL/rGjPYe3kh8NbM4rLNZR2DIWGlPgZJtj8pEZhr3u1kqkRN9HWuU8A4AY4Kykinu6WJvSm2WYttgmHvgwDO5kokoF7hIaLZJ7Td914HCf3Hp8ajDHSknNJoeuyKIElEOCSW/+Pe3FN+u7i4GBVkszeHzNFPcXm8cpS8CtNAy32L+Dt31lVBMxEjexogQiO51EJfEgU03odKlRHs+Ws1F2K5bm/klSzLITcEzG2vygk99bmbbkVdr7o//cqqMfN5Nm3ig/04Gm6+n1lKQnOe1nMxEbhgPfWig2BbLQI6hPFvqijZniTXsz+bruvczxymd9sIUwODo52Cv88ufcRo0NpRi16L0V6p+znK4COJ6YvMizqUuMPeDwQDc2i7k5yeLwk79nJ0wHlEwijrtalGnOmCdZyonpFVXdqro3JoHf1YCq7aSOfj0GjaOw62/v5877oOqk9mv/1/V238xaS+uvCCy81lQWlNzYxAnXyuNrjkHxbkpjzhRKlRNYIfzwX35Fm+Uzids3KvyIFnFNLpYh8oQLT44IWtlUViSbtBqDMhobGySJr/LtNPHcZ++havKquxMtYknSXf7wXdis=
  file:
    - dist/icecast.js
    - dist/icecast.min.js
  on:
    repo: jucrouzet/icecast.js
    tags: true
